name: WARP2 semantic test runner

on:
  push:
    branches:
      - autoTest-RUN

env:
  CAIRO_LANG_VERSION: 0.8.2.1

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          cache: 'yarn'

      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.7 # Cairo was tested with this version

      - name: Install dependencies
        run: |
          make
          make compile

      - name: Setup warp_venv
        run: bin/warp install --python python --verbose

      - name: Build warplib
        run: yarn warplib

      - name: Run semantic tests
        run: node ./build/autoRunSemanticTests.js
